export default interface ProductInterface {
  id: number; // autogenerated by postgres
  title: string;
  price: number;
  description: string;
  // TODO! Sacar string to type img
  image?: string;
  rating: number;
}
